# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-12 08:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpotList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('note', models.TextField(blank=True)),
                ('estimatedCost', models.DecimalField(blank=True, decimal_places=0, max_digits=5)),
                ('estimatedTime', models.DecimalField(blank=True, decimal_places=0, max_digits=5)),
                ('picture', models.TextField(blank=True)),
                ('spotType', models.DecimalField(decimal_places=0, max_digits=1)),
                ('spotName', models.CharField(blank=True, max_length=100)),
                ('spotAddress', models.CharField(blank=True, max_length=100)),
                ('transportationType', models.DecimalField(blank=True, decimal_places=0, max_digits=1)),
                ('startPlace', models.CharField(blank=True, max_length=100)),
                ('endPlace', models.CharField(blank=True, max_length=100)),
                ('hotelName', models.CharField(max_length=100)),
                ('hotelAddress', models.CharField(blank=True, max_length=100)),
                ('checkinTime', models.DateTimeField(blank=True)),
                ('checkoutTime', models.DateTimeField(blank=True)),
                ('restaurantName', models.CharField(blank=True, max_length=100)),
                ('restaurantNote', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TravelList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('days', models.DecimalField(decimal_places=0, max_digits=3)),
                ('nights', models.DecimalField(decimal_places=0, max_digits=3)),
                ('startTime', models.DateTimeField()),
                ('backTime', models.DateTimeField()),
                ('place', models.TextField(blank=True)),
                ('estimatedCost', models.DecimalField(decimal_places=0, max_digits=5)),
                ('member', models.TextField(blank=True)),
                ('note', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='spotlist',
            name='travelListId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.TravelList'),
        ),
    ]
