# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-14 13:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='spotlist',
            name='describe',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='spotlist',
            name='urllinks',
            field=models.TextField(blank=True),
        ),
    ]
