# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-04 06:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SheetList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=100)),
                ('link', models.URLField(blank=True)),
                ('picture', models.URLField(blank=True)),
                ('describe', models.TextField(blank=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
