# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 03:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetupload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetlist',
            name='tag',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sheetlist',
            name='source',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
