# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-16 03:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sheetupload', '0002_auto_20170216_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='sheetlist',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sheetlist',
            name='difficulty',
            field=models.DecimalField(blank=True, decimal_places=0, default=django.utils.timezone.now, max_digits=1),
            preserve_default=False,
        ),
    ]
