# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-17 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sheetupload', '0005_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='sheetlist',
            name='isPublic',
            field=models.BooleanField(default=True),
        ),
    ]
